id: A0B609189
title: Toh_115-The_Display_of_the_Pure_Land_of_Sukhavati-v1
type: translation
pechas:
- IEC3955C0
- I35302A89
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-03-26T15:37:56.261Z'
  creationid: celso
  eft-text-id: UT22084-051-003
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_115-The_Display_of_the_Pure_Land_of_Sukhavati-v1
alignment_to_base:
  IEC3955C0/767E: '9105'
  I35302A89/944E: '9105'
